spring:
  application:
    name: member-service
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info